### ISSUE TITLE
Donate: "Other Sum" is not a mandatory field

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#55] opened 2017-09-12 12:09 UTC
After selecting a custom (other) sum, a user is not required to input the amount he wishes to donate.
Nor is this field required to be full in order to proceed.
This causes a bug later in the flow:

http://prntscr.com/gk78g4

Reproduce:

1. Enter donation flow.
2. Select "other sum".
3. Leave the field blank
4. Click continue.

Expected:
1. User prevented from continuing without providing an amount.

Actual:
1. User continues, recieves this on next page: http://prntscr.com/gk78g4

**Comment by ibanner** [comment] 2017-09-27 08:30
@TheGrandVizier The "Continue" button will initially be disabled, and will be enabled only when a valid donation sum is selected or manually entered. Closing.

**Comment by nuritgazit** [comment] 2017-09-27 08:31
@ibanner please don't close issues, @TheGrandVizier will do it if he checks and confirms the issue is indeed closed. thanks!

**Comment by ibanner** [comment] 2017-09-27 08:41
@nuritgazit His excellency @TheGrandVizier instructed me to close issues I'm fixing. All my commits are pending review under the pull request - #57 .

**Comment by TheGrandVizier** [comment] 2017-10-19 09:15
@nuritgazit 
Dont worry. We good.

**Closed** 2017-10-19 09:15 UTC
